### ISSUE TITLE
gapi.client.tasks has an invalid structure

### ISSUE THREAD

**Issue by EdricChan03** [Bolisov/google-api-typings-generator#12]
I'm currently creating an Angular app that allows you to import Google Tasks. However, the structure of the TypeScript definition file has an invalid structure.

Currently, the structure of the actual `gapi.client.tasks` object is as follows:

```
gapi.client.tasks {
  tasks: ...
  tasklists: ...
}
```

However, the TypeScript definitions file defined it as follows:

```
gapi.client {
  tasks: ...
  tasklists: ...
}
```

It seems that the root is one level up.

From the other issues, it seems that this is prevalent for all of the TypeScript definitions. Please fix ASAP.

EDIT: It seems that the author of this repository (@Bolisov) has been inactive for over a year now. I don't think any of the issues will be fixed..

**Comment by Maxim-Mazurok** [comment]
Hello Edric, thanks for opening issue!
You noticed correctly, this repo is not maintained, so please, open new issues in our active fork: [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator)

I've made this repo with an example on how you can use Google Tasks API with TypeScript for Browser: [Maxim-Mazurok/google-tasks-api-ts-example](https://github.com/Maxim-Mazurok/google-tasks-api-ts-example)

Please note, that I just submitted PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41530 to update Google Tasks API typings, so right now my example will not work.

To make it work, you should either wait for my PR to be merged and NPM package updated.
Or, just put this file somewhere in your project: [Google Tasks API v1 1.0 - index.d.ts](https://gist.github.com/Maxim-Mazurok/9013404d82540945a3648a7798287e20)

Let me know if you have any questions, I'll be happy to help, cheers!

**Comment by EdricChan03** [comment]
Hey @Maxim-Mazurok, thanks for updating the generator code! I've generated a local version of the Google Tasks API a while back after I discovered your forked repository and found that it works!

**Comment by EdricChan03** [comment]
Looks like DefinitelyTyped/DefinitelyTyped#41530 has been merged, so I'll close this issue.

Once again, thanks @Maxim-Mazurok for helping to update the types for the `gapi` JavaScript client for the Google Tasks API! 🥳
