### ISSUE TITLE
ga.client.analytics has the wrong structure

### ISSUE THREAD

**Issue by Lucretiel** [Bolisov/google-api-typings-generator#7]
The type signature for `gapi.client.analytics` (here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.client.analytics/index.d.ts) claims the following structure:

```
gapi.client.metadata
gapi.client.provisioning
```
etc.

However, the actual structure includes the `analytics` namespace, like so:

```
gapi.client.analytics.metadata
gapi.client.analytics.provisioning
```

etc

**Comment by moshest** [comment]
Temporary fix:

```ts

declare let window: Window & {
  gapi: typeof gapi & {
    client: typeof gapi.client & {
      analytics: {
        data: gapi.client.analytics.DataResource;
        management: gapi.client.analytics.ManagementResource;
        metadata: gapi.client.analytics.MetadataResource;
        provisioning: gapi.client.analytics.ProvisioningResource;
      }
    };
  };
};

const { gapi } = window;
```

**Comment by Maxim-Mazurok** [comment]
This repo is abandoned, see #19 and use active fork instead: [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator)

Please, close this issue if you will, thanks for your cooperation!
